#ifndef RINGBUFFER_DMA_PAROL_H_INCLUDED
#define RINGBUFFER_DMA_PAROL_H_INCLUDED

	//#define WIFI_SSID				"Tapac"
	#define WIFI_SSID				"Kobza-Main"
	#define WIFI_PASS				"27051329"

	#define THINGSPEAK_ADDRESS		"api.thingspeak.com"

#if ( FIRST8 == 1 )
	#define THINGSPEAK_API_KEY_0	"5ZRXVI7HIJQPGKID"
	#define THINGSPEAK_API_KEY_1	"T6WU172VUJS77Z55"
	#define THINGSPEAK_API_KEY_2	"4LFGIANKKBDAZJWT"
	#define THINGSPEAK_API_KEY_3	"EFQQ1RM154LLUX19"

#elif ( NEXT12 == 1)
	#define THINGSPEAK_API_KEY_0	"58O6BKYQEOWDRE6T"
	#define THINGSPEAK_API_KEY_1	"GKO4OO4NQBZZ4KSZ"
	#define THINGSPEAK_API_KEY_2	"VF46PD6BDUF9QQZV"
	#define THINGSPEAK_API_KEY_3	"840Q0CH1KWST2EWN"
#endif

#endif
