#ifndef RINGBUFFER_DMA_PAROL_H_INCLUDED
#define RINGBUFFER_DMA_PAROL_H_INCLUDED

	#define WIFI_SSID				"Tapac"
	#define WIFI_PASS				"27051329"

	#define THINGSPEAK_ADDRESS		"api.thingspeak.com"

	#define THINGSPEAK_API_KEY_1	"5ZRXVI7HIJQPGKID"
	#define THINGSPEAK_API_KEY_2	"T6WU172VUJS77Z55"
	#define THINGSPEAK_API_KEY_3	"4LFGIANKKBDAZJWT"

	#define THINGSPEAK_API_KEY_4	"58O6BKYQEOWDRE6T"
	#define THINGSPEAK_API_KEY_5	"GKO4OO4NQBZZ4KSZ"
	#define THINGSPEAK_API_KEY_6	"VF46PD6BDUF9QQZV"
	#define THINGSPEAK_API_KEY_7	"840Q0CH1KWST2EWN"

#endif


